import type { Program, Tier } from "./covenant";

export const PROGRAMS: Program[] = [
  {
    key: "board",
    name: "Needs & Offers Board",
    tier: 0,
    status: "live",
    route: "/board",
    summary: "A public board of who needs what and who has what, by category and locality.",
    why: "The first casualty of collapse is coordination; the second is trust. A shared list of needs and offers is the minimum viable society. Everything else builds on it.",
    features: ["Post a need or an offer", "Pure barter: what would you take in return?", "Optional Grace or Hours ask", "Pledge to meet a need or take an offer", "Survival needs surfaced first"],
  },
  {
    key: "map",
    name: "Map & Distance",
    tier: 0,
    status: "live",
    route: "/map",
    summary: "A pin chosen on a map at join, no address, no forced GPS. Needs, offers, commons and hazards drawn around you; people shown only as a distance.",
    why: "Mutual aid is physical: who is close enough to carry water tonight. But a map of where everyone sleeps is exactly what a hostile state wants. So pins are rounded to a hundred meters, people are never drawn, and only what someone chose to publish appears on the map.",
    features: ["OpenStreetMap pin picker at join", "Pins rounded to ~100 m", "Distance on every card", "Within-10-km scope", "Hazard radius circles", "Local tile server via NEXT_PUBLIC_TILE_URL"],
  },
  {
    key: "trust",
    name: "Web of Trust",
    tier: 0,
    status: "live",
    route: "/people",
    summary: "Identity is who vouches for you. A person is verified once enough locals vouch (about the square root of the locality over three: 1 at 5 people, 3 at 100, never more than 7).",
    why: "With no ID authority, the only proof of a person is other people. Vouching makes fake identities expensive and makes standing something you earn from neighbors rather than receive from an office.",
    features: ["Vouch for a person, with a note", "Verification threshold scales with locality", "Only verified people can vouch, keep, or vote", "Standing score and tier", "Credit limits derived from standing"],
  },
  {
    key: "bulletins",
    name: "Bulletins & Hazards",
    tier: 0,
    status: "live",
    route: "/bulletins",
    summary: "Local alerts and notices, each signed by a named person with standing.",
    why: "Rumor kills. Contaminated water, armed groups, blocked roads, a clinic opening: one place, named authors, expiry dates.",
    features: ["Info / Hazard / Urgent levels", "Locality tagging", "Expiry", "Author visible"],
  },
  {
    key: "responders",
    name: "Skills & Responders Registry",
    tier: 0,
    status: "live",
    route: "/people",
    summary: "Who can set a bone, purify water, fix a generator, deliver a baby.",
    why: "In an emergency the question is never what do we have, but who knows how. Skills are on every profile and searchable.",
    features: ["Skills on profile", "Search people by skill", "Locality filter"],
  },
  {
    key: "grace",
    name: "Grace (GRC) Mutual Credit",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "A coin nobody issues, written with an olive-sprig mark (GRC in plain text). Grace is created when one person serves another and destroyed when the favor is returned. All balances always sum to zero.",
    why: "Barter fails on the double coincidence of wants. Fiat needs a state. Metal needs a vault. Mutual credit needs only a ledger and trust: no issuer can inflate it, no treasury can be seized (there is none), and it cannot be hoarded to starve others because credit limits are set by standing, not wealth.",
    features: ["Pay anyone by username", "Negative balances up to a standing-based limit", "Demurrage: positive balances decay 3% a month into an equal dividend for verified members", "Full history", "Settle board listings on completion"],
  },
  {
    key: "hours",
    name: "Hours Time Bank",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "One hour equals one hour, for everyone. Childcare and carpentry are worth the same.",
    why: "Some things should not be priced. A second ledger where every hour is equal keeps dignity in the poorest and keeps care work visible.",
    features: ["Hours ledger alongside Grace", "Minute-level precision", "Standing-based limits"],
  },
  {
    key: "commons",
    name: "Commons Stewardship",
    tier: 1,
    status: "live",
    route: "/commons",
    summary: "Wells, tool libraries, seed banks, clinics, kitchens. Stewards, not owners.",
    why: "Private hoarding and state ownership both fail under collapse. A named steward accountable to users, with rules those users agreed to, is how commons have actually survived for centuries.",
    features: ["Register a commons with rules", "Steward accountable via standing", "Availability toggle"],
  },
  {
    key: "circles",
    name: "Circles",
    tier: 1,
    status: "live",
    route: "/circles",
    summary: "Restorative process for harm. Keepers drawn by lot from people of standing. Account, listening, restitution, public record. Never a cage.",
    why: "Without police or courts, the alternative to a restorative process is vendetta. Circles make harm public, heard, and repaired, and their outcomes feed back into standing.",
    features: ["Raise a circle about a harm", "Keepers drawn by lot from a pool that grows with the square root of the locality", "Outcomes: harm found, no harm, unfounded", "Unfounded accusations cost the accuser standing", "Accusation credit: only so many circles open at once"],
  },
  {
    key: "rotas",
    name: "Care & Watch Rotas",
    tier: 2,
    status: "planned",
    summary: "Rotating shifts for night watch, childcare, elder care, kitchen. Nobody guards forever.",
    why: "Whoever holds the weapons full-time becomes the government. Rotation is the structural defense against a security class.",
    features: ["Rota templates", "Sign-up and swap", "Paid in Hours", "Rotation enforced by design"],
  },
  {
    key: "assemblies",
    name: "Assemblies",
    tier: 2,
    status: "live",
    route: "/assemblies",
    summary: "Questions put to a locality, decided by ranked-choice (instant runoff) voting among verified people.",
    why: "Some things a locality must decide together. Ranked choice lets people say what they can live with, not only what they want most, and the runoff finds the option a majority can accept.",
    features: ["Locality-scoped proposals", "Ranked ballots, changeable until close", "Instant-runoff tally with rounds shown", "Results hidden until close", "Verified voters only"],
  },
  {
    key: "library",
    name: "Knowledge Library",
    tier: 2,
    status: "planned",
    summary: "Offline-first manuals: water, medicine, food preservation, radio, agriculture, repair.",
    why: "Knowledge is the one resource that grows when shared. It must be available when the network is not.",
    features: ["Markdown manuals", "Offline bundle export", "Attribution and vouching for accuracy"],
  },
  {
    key: "mesh",
    name: "Mesh & Offline Sync",
    tier: 2,
    status: "planned",
    summary: "The app must outlive the internet: sync over LAN, mesh radio, or a USB stick.",
    why: "A hostile government moves on the network first. A single server is a single point of seizure. The ledger and board must be replicable, signed, and mergeable across nodes.",
    features: ["Signed records", "CRDT/merge for board and bulletins", "Ledger reconciliation", "Node-to-node sync"],
  },
  {
    key: "apprentice",
    name: "Apprenticeships",
    tier: 2,
    status: "planned",
    summary: "Turn the skills registry into teaching. Paid in Hours.",
    why: "A society stays stateless only as long as its skills are not scarce enough to be captured.",
    features: ["Teacher/learner pairing", "Progress log", "Hours settlement"],
  },
];

export const programsByTier = (tier: Tier) => PROGRAMS.filter((p) => p.tier === tier);
