import type { Program, Tier } from "./covenant";

export const PROGRAMS: Program[] = [
  {
    key: "board",
    name: "Needs & Offers Board",
    tier: 0,
    status: "live",
    route: "/board",
    summary: "A public board of who needs what and who has what, by category and locality.",
    why: "The first casualty of collapse is coordination; the second is trust. A shared list of needs and offers is the minimum viable society. Everything else builds on it.",
    features: ["Post a need or an offer", "Pure barter: what would you take in return?", "Optional Grace or Hours ask", "Pledge to meet a need or take an offer", "Survival needs surfaced first", "Match finding: counterpart suggestions and direct two-way trades"],
  },
  {
    key: "map",
    name: "Map & Distance",
    tier: 0,
    status: "live",
    route: "/map",
    summary: "A pin chosen on a map at join, no address, no forced GPS. Needs, offers, commons and hazards drawn around you; people shown only as a distance.",
    why: "Mutual aid is physical: who is close enough to carry water tonight. But a map of where everyone sleeps is exactly what a hostile state wants. So pins are rounded to a hundred meters, people are never drawn, and only what someone chose to publish appears on the map.",
    features: ["OpenStreetMap pin picker at join", "Pins rounded to ~100 m", "Distance on every card", "Within-10-km scope", "Hazard radius circles", "Local tile server via NEXT_PUBLIC_TILE_URL"],
  },
  {
    key: "trust",
    name: "Web of Trust",
    tier: 0,
    status: "live",
    route: "/people",
    summary: "Identity comes from vouches. A person is verified once enough locals vouch (about the square root of the locality over three: 1 at 5 people, 3 at 100, never more than 7).",
    why: "With no ID authority, the only proof of a person is other people. Vouching makes fake identities expensive and makes standing something you earn from neighbors rather than receive from an office.",
    features: ["Vouch for a person, with a note", "Verification threshold scales with locality", "Only verified people can vouch, mediate, or vote", "Standing score and tier", "Credit limits derived from standing", "Optional ID.me affiliation verification: one extra vouch, never required, off by default"],
  },
  {
    key: "bulletins",
    name: "Bulletins & Hazards",
    tier: 0,
    status: "live",
    route: "/bulletins",
    summary: "Local alerts and notices, each signed by a named person with standing.",
    why: "Rumor kills. Contaminated water, armed groups, blocked roads, a clinic opening: one place, named authors, expiry dates.",
    features: ["Info / Hazard / Urgent levels", "Locality tagging", "Expiry", "Author visible"],
  },
  {
    key: "responders",
    name: "Skills & Responders Registry",
    tier: 0,
    status: "live",
    route: "/people",
    summary: "Who can set a bone, purify water, fix a generator, deliver a baby - self-listed skills plus optional ID.me-verified affiliations.",
    why: "In an emergency the question is never what do we have, but who knows how. Skills are on every profile and searchable.",
    features: ["Skills on profile", "Search people by skill or verified affiliation", "Optional ID.me affiliation badges (nurse, first responder, teacher, government, military)", "Locality filter"],
  },
  {
    key: "grace",
    name: "Grace (GRC) Mutual Credit",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "Community credit with an olive-sprig symbol (GRC in plain text). Grace is created when one person helps another and settled when the favor is returned; all balances sum to zero.",
    why: "Barter fails on the double coincidence of wants. Fiat needs a state. Metal needs a vault. Mutual credit needs only a ledger and trust: no issuer can inflate it, no treasury can be seized (there is none), and it cannot be hoarded to starve others because credit limits are set by standing, not wealth.",
    features: ["Pay anyone by username", "Negative balances up to a standing-based limit", "Demurrage: positive balances decay 3% a month into an equal dividend for verified members", "Full history", "Settle board listings on completion"],
  },
  {
    key: "pulse",
    name: "Trade Pulse",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "After each settled exchange, both people answer one question: did it leave you better off? The community total is public.",
    why: "The classroom experiment: rate what you were handed, trade freely, rate again, and the total rises. Exchange creates value without creating goods. Measuring that, in the open, is how a community sees that its ledger summing to zero is not the same as nobody gaining.",
    features: ["One private answer per person per exchange", "Aggregates only, never individual answers", "Never affects standing", "30-day and all-time totals on the ledger"],
  },
  {
    key: "trustpreview",
    name: "Trust Preview",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "Before you pay or extend credit, see what the other person already owes the commons, their standing, kept pledges, and any resolved harm.",
    why: "Credit without visibility is how a community gets drained by one bad actor. Everything here is already public; the preview just puts it in front of you at the moment of decision, so you can see that someone is already at their limit before you hand them more.",
    features: ["Look up anyone before paying", "Balance, owe-limit, standing, kept pledges, vouches", "Plain-language risk flags", "No private data, only what the ledger already shows"],
  },
  {
    key: "ledgerlog",
    name: "Tamper-evident Ledger",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "Every transfer, dividend, and voucher event is hash-chained. The whole history fingerprints to one root, so any later edit is evident to anyone who checks.",
    why: "A single server could, in principle, quietly rewrite the past. Chaining each entry to the one before it means altering any record breaks every hash after it and moves the root. Publish or remember the root and tampering cannot hide. Integrity without a blockchain, mining, or a token.",
    features: ["sha256 hash chain over all economic events", "Root shown on the ledger", "Full re-derivation from the underlying records", "Detects edited records and edited log entries"],
  },
  {
    key: "cash",
    name: "Cash (hash-locked notes)",
    tier: 2,
    status: "live",
    route: "/cash",
    summary: "Denominated bearer notes locked by a secret only the holder keeps. Your device makes and hashes the secret; the commons stores only the hash, so it can never spend a note for you.",
    why: "This is the most self-custodial money here and the closest to cash. Because the system holds only a commitment, not the secret, even a seized server cannot forge redemptions of notes in the wild. You mint (which burns the value into the commitment), write the note down, and whoever reveals the secret reclaims it. Lose the paper and it is gone, exactly like cash - and exactly the fail-safe of self-custody.",
    features: ["Secret generated and hashed in your browser, never sent until spent", "Fixed denominations bound into the hash", "Mint burns value to a commitment; reveal reclaims it", "Single-use: a copy is caught on reclaim", "Printable note with QR"],
  },
  {
    key: "checkpoint",
    name: "Portable Ledger Checkpoints",
    tier: 2,
    status: "live",
    route: "/verify",
    summary: "The whole hash-chained ledger, signed by the commons and downloadable, so anyone can verify the history off-server on any machine.",
    why: "A server can be seized or coerced. Exporting the signed chain of hashes lets the ledger's integrity be checked without trusting the server at all, and lets the history travel onto another node or a USB stick. Publish a checkpoint and the past can never be quietly rewritten. The foundation for node-to-node sync when the network is gone.",
    features: ["Commons-signed Merkle root (checkpoint)", "Download the full signed chain", "Verify on any machine with only the public key", "Re-derives the chain and checks the signature", "Reveals no private data, only commitments"],
  },
  {
    key: "vouchers",
    name: "Offline Vouchers",
    tier: 2,
    status: "live",
    route: "/vouchers",
    summary: "Retired: commons-signed notes, replaced by Cash (which you hold yourself). Existing notes can still be redeemed.",
    why: "When the network is down, value still has to move. A note carrying a real signature (not a bare hash) can be verified offline against the commons public key, and its single-use serial makes a photocopy detectable the second time. Double-spend becomes catchable rather than free.",
    features: ["Ed25519-signed notes with QR", "Single-use serial (nonce)", "Issue reserves from your balance; void refunds it", "Verify against the published commons key", "Redeem checks signature before anything moves"],
  },
  {
    key: "jubilee",
    name: "Jubilee / Wind-down",
    tier: 2,
    status: "live",
    route: "/wind-down",
    summary: "A mirror showing that dissolving the commons costs no one: debts forgiven, credits released, everyone back to zero together.",
    why: "You asked for a fail-safe where failure is shared evenly. Mutual credit already has it: because balances net to zero, the cost of collapse is zero for each person, and there is no treasury for a hostile authority to seize. Making it visible is reassurance you can check any day.",
    features: ["Live wind-down report", "Debt forgiven and claims released", "Proof the books net to zero", "A mirror, never a one-click switch"],
  },
  {
    key: "hours",
    name: "Hours Time Bank",
    tier: 1,
    status: "live",
    route: "/ledger",
    summary: "One hour equals one hour, for everyone. Childcare and carpentry are worth the same.",
    why: "Some things should not be priced. A second ledger where every hour is equal keeps dignity in the poorest and keeps care work visible.",
    features: ["Hours ledger alongside Grace", "Minute-level precision", "Standing-based limits"],
  },
  {
    key: "seeds",
    name: "Seed Bank & Plant Exchange",
    tier: 1,
    status: "live",
    route: "/seeds",
    summary: "A living library of locally saved seed, seedlings, cuttings, and tubers, shared as a gift with a return-at-harvest custom.",
    why: "A community that cannot save its own seed depends on someone who sells it. Open-pollinated, locally adapted seed is the difference between eating next year and not. The take-one-return-more custom means the bank grows with use instead of running down.",
    features: ["Variety metadata: form, type, open-pollinated vs hybrid, days to maturity", "Sow-this-month seasonal filter", "Gift-first request, then grow, then return seed at harvest", "Locality and within-10-km scope", "Returns tracked so reliable growers are visible"],
  },
  {
    key: "commons",
    name: "Commons Stewardship",
    tier: 1,
    status: "live",
    route: "/commons",
    summary: "Wells, tool libraries, seed banks, clinics, kitchens. Stewards, not owners.",
    why: "Private hoarding and state ownership both fail under collapse. A named steward accountable to users, with rules those users agreed to, is how commons have actually survived for centuries.",
    features: ["Register a commons with rules", "Steward accountable via standing", "Availability toggle"],
  },
  {
    key: "circles",
    name: "Disputes",
    tier: 1,
    status: "live",
    route: "/circles",
    summary: "A public process for harm: mediators drawn at random, everyone heard, an agreed repair written down.",
    why: "Without police or courts, the alternative to a fair process is retaliation. Disputes make harm public, heard, and repaired, and their outcomes feed back into standing.",
    features: ["Open a dispute about a harm", "Mediators drawn by public lottery seeded from the drand randomness beacon; every draw is logged and recomputable", "Outcomes: harm found, no harm, unfounded", "Unfounded claims cost the claimant standing", "Only so many open disputes per person"],
  },
  {
    key: "rotas",
    name: "Care & Watch Rotas",
    tier: 2,
    status: "planned",
    summary: "Rotating shifts for night watch, childcare, elder care, kitchen. Nobody guards forever.",
    why: "A permanent guard turns into a ruling class. Rotating the duty is the structural defense against that.",
    features: ["Rota templates", "Sign-up and swap", "Paid in Hours", "Rotation built in"],
  },
  {
    key: "assemblies",
    name: "Assemblies",
    tier: 2,
    status: "live",
    route: "/assemblies",
    summary: "Questions put to a locality, decided by ranked-choice (instant runoff) voting among verified people.",
    why: "Some things a locality must decide together. Ranked choice lets people say what they can live with, not only what they want most, and the runoff finds the option a majority can accept.",
    features: ["Locality-scoped proposals", "Ranked ballots, changeable until close", "Instant-runoff tally with rounds shown", "Results hidden until close", "Verified voters only"],
  },
  {
    key: "library",
    name: "Knowledge Library",
    tier: 2,
    status: "planned",
    summary: "Offline-first manuals: water, medicine, food preservation, radio, agriculture, repair.",
    why: "Knowledge is the one resource that grows when shared. It must be available when the network is not.",
    features: ["Markdown manuals", "Offline bundle export", "Attribution and vouching for accuracy"],
  },
  {
    key: "mesh",
    name: "Mesh & Offline Sync",
    tier: 2,
    status: "planned",
    summary: "The app must outlive the internet: sync over LAN, mesh radio, or a USB stick.",
    why: "A hostile government moves on the network first. A single server is a single point of seizure. The ledger and board must be replicable, signed, and mergeable across nodes.",
    features: ["Signed records", "CRDT/merge for board and bulletins", "Ledger reconciliation", "Node-to-node sync"],
  },
  {
    key: "apprentice",
    name: "Apprenticeships",
    tier: 2,
    status: "planned",
    summary: "Turn the skills registry into teaching. Paid in Hours.",
    why: "A society stays stateless only as long as its skills are not scarce enough to be captured.",
    features: ["Teacher/learner pairing", "Progress log", "Hours settlement"],
  },
];

export const programsByTier = (tier: Tier) => PROGRAMS.filter((p) => p.tier === tier);
